### PR TITLE
fix: Advanced filters does not contain tags after first tag was added (@Rowan441)

### LINKED ISSUE #6972: Advanced filters does not contain tags after first tag was added
- account with no tags
- add first tag
- go to advanced filters, tag filter  is missing
- works after reloading the page

### PR DESCRIPTION
**Pull request by Rowan441**
### Description

fixes #6972

The setup logic for the "tags", "funbox", and "language" advanced filters are only run on the first load. So adding a tag in the /settings won't make the "tags" multiselect render when you navigate back to the /account page unless you reload.

Added logic to add / destroy the "tags" multiselect if you create your first tag or delete your last tag.

### Checks

- [ ] Adding quotes?
  - [ ] Make sure to include translations for the quotes in the description (or another comment) so we can verify their content.
- [ ] Adding a language?
  - Make sure to follow the [languages documentation](https://github.com/monkeytypegame/monkeytype/blob/master/docs/LANGUAGES.md)
  - [ ] Add language to `packages/schemas/src/languages.ts`
  - [ ] Add language to exactly one group in `frontend/src/ts/constants/languages.ts`
  - [ ] Add language json file to `frontend/static/languages` 
- [ ] Adding a theme?
  - Make sure to follow the [themes documentation](https://github.com/monkeytypegame/monkeytype/blob/master/docs/THEMES.md)
  - [ ] Add theme to `packages/schemas/src/themes.ts`
  - [ ] Add theme to `frontend/src/ts/constants/themes.ts`
  - [ ] Add theme css file to `frontend/static/themes`
  - [ ] Add some screenshot of the theme, especially with different test settings (colorful, flip colors) to your pull request  
- [ ] Adding a layout?
  - [ ] Make sure to follow the [layouts documentation](https://github.com/monkeytypegame/monkeytype/blob/master/docs/LAYOUTS.md)
  - [ ] Add layout to `packages/schemas/src/layouts.ts`
  - [ ] Add layout json file to `frontend/static/layouts` 
- [ ] Adding a font?
  - Make sure to follow the [themes documentation](https://github.com/monkeytypegame/monkeytype/blob/master/docs/FONTS.md)
  - [ ] Add font file  to `frontend/static/webfonts`
  - [ ] Add font to `packages/schemas/src/fonts.ts`
  - [ ] Add font to `frontend/src/ts/constants/fonts.ts`
- [x] Check if any open issues are related to this PR; if so, be sure to tag them below.
- [x] Make sure the PR title follows the Conventional Commits standard. (https://www.conventionalcommits.org for more info)
- [x] Make sure to include your GitHub username prefixed with @ inside parentheses at the end of the PR title.

Closes #6972

### CODE REVIEW

File: frontend/src/ts/elements/account/result-filters.ts [hunk 1]
```diff
@@ -864,60 +869,58 @@ export async function appendButtons(
...
-export function removeButtons(): void {
-  $(
-    ".pageAccount .content .filterButtons .buttonsAndTitle.languages .buttons"
-  ).empty();
-  $(
-    ".pageAccount .content .filterButtons .buttonsAndTitle.funbox .buttons"
-  ).empty();
-  $(
-    ".pageAccount .content .filterButtons .buttonsAndTitle.tags .buttons"
-  ).empty();
```
Comment (Rowan441) [inline frontend/src/ts/elements/account/result-filters.ts:920]: This doesn't do anything anymore. I guess the buttons were swapped out for SlimSelect at some point.

Also renamed `appendButtons` to `appendDropdowns` for consistency

**Comment by Rowan441** [comment]
Extracted into a function!

I also:
Removed some old code from when the dropdowns were buttons and renamed `appendButton` to `appendDropdown`
Moved `updateTagsDropdownOptions` call from `beforeShow` on account page, to inside the `appendDropdown` function
