### PR TITLE
fix(config): auto-resolve monkey live stats conflicts (@d1rshan)

### LINKED ISSUE #7714: UI: Monkey overlaps live speed/live accuracy when those stats use text style
### Did you clear cache before opening an issue?

- [x] I have cleared my cache

### Is there an existing issue for this?

- [x] I have [searched](https://github.com/monkeytypegame/monkeytype/issues?q=is%3Aissue) the existing open and closed issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

d1rsh

### Account config

_No response_

### Current Behavior

The monkey overlaps the live speed/live accuracy text.

Image

### Expected Behavior

The UI should prevent unsupported combinations by showing a toast notification

### Steps To Reproduce

1. Open settings (command line / settings page)
2. Set live speed style to text and/or live accuracy style to text
3. Enable monkey
4. Start a test

### Environment

_No response_

### Anything else?

The overlap happens for:
  - live speed text + monkey
  - live accuracy text + monkey
  - both text stats + monkey

### PR DESCRIPTION
**Pull request by d1rshan**
Adds handling for the invalid monkey + live text stats combination by auto-resolving conflicting settings instead of blocking them.

  Behavior:
  - enabling monkey while live speed style or live accuracy style is text will automatically set those conflicting live stat styles to off
  - setting live speed style to text while monkey is enabled will automatically disable monkey
  - setting live accuracy style to text while monkey is enabled will automatically disable monkey

  This follows the existing overrideConfig pattern used for other conflicting settings, where the latest selection takes priority.

Also adds tests to cover these auto-resolved config combinations.

Closes #7714

### CODE REVIEW

**Comment by d1rshan** [comment]
hey @Miodec, just following up on this PR, it fixes #7714. lmk if you want any changes

**Comment by Miodec** [comment]
I think blocking the config change is a bit overkill, but also im not sure whats the best way of handling this. Maybe just allow the overlap and let the user deal with it.

**Comment by d1rshan** [comment]
understandable, what if we automatically resolve conflicting settings by disabling the existing one when another is enabled, with a toast to inform the user. (priority for latest selection)

**Comment by Miodec** [comment]
Thats how confidence and freedom mode work, maybe we could try that 

image

**Comment by d1rshan** [comment]
> Thats how confidence and freedom mode work, maybe we could try that 
> 
> 
> 
> image
> 
> 

updated for this behaviour!

File: frontend/src/ts/config/metadata.ts [hunk 1]
```diff
@@ -1005,6 +1021,21 @@ export const configMetadata: ConfigMetadataObject = {
...
+        return {
+          liveSpeedStyle:
+            currentConfig.liveSpeedStyle === "text"
+              ? "off"
+              : currentConfig.liveSpeedStyle,
+          liveAccStyle:
+            currentConfig.liveAccStyle === "text"
+              ? "off"
+              : currentConfig.liveAccStyle,
+        };
```
Comment (Miodec) [inline frontend/src/ts/config/metadata.ts:1035]: Change to mini, not off.

**Review by Miodec — CHANGES_REQUESTED** [review]
Thanks

File: frontend/src/ts/config/metadata.ts (hunk 1 above)
Comment (d1rshan) [reply frontend/src/ts/config/metadata.ts:1035]: done

**Comment by Miodec** [comment]
Thanks
